image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: off

install:

  - java -jar ./artifacts/app-mbank.jar &

build_script:
  - ./gradlew test --info

  notifications:
      provider: Email

        to:
          - m.kriklivenko@gmail.com

        on_build_success: false

        on_build_failure: true

        on_build_status_changed: true